// FILE IS GENERATED FROM docs/hyprspace-*.adoc files
// TO REGENERATE THE FILE RUN generate.sh --all

// Temporary stubs for build (docs not yet generated)
let balance_sizes_help_generated = ""
let close_all_windows_but_current_help_generated = ""
let close_help_generated = ""
let config_help_generated = ""
let debug_windows_help_generated = ""
let enable_help_generated = ""
let exec_and_forget_help_generated = ""
let flatten_workspace_tree_help_generated = ""
let focus_back_and_forth_help_generated = ""
let focus_help_generated = ""
let focus_monitor_help_generated = ""
let fullscreen_help_generated = ""
let join_with_help_generated = ""
let layout_help_generated = ""
let list_apps_help_generated = ""
let list_exec_env_vars_help_generated = ""
let list_modes_help_generated = ""
let list_monitors_help_generated = ""
let list_windows_help_generated = ""
let list_workspaces_help_generated = ""
let macos_native_fullscreen_help_generated = ""
let macos_native_minimize_help_generated = ""
let mode_help_generated = ""
let move_help_generated = ""
let move_mouse_help_generated = ""
let move_node_to_monitor_help_generated = ""
let move_node_to_workspace_help_generated = ""
let move_workspace_to_monitor_help_generated = ""
let reload_config_help_generated = ""
let resize_help_generated = ""
let split_help_generated = ""
let summon_workspace_help_generated = ""
let swap_help_generated = ""
let trigger_binding_help_generated = ""
let volume_help_generated = ""
let workspace_back_and_forth_help_generated = ""
let workspace_help_generated = ""
